spring.application.name=saleapplication


# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/agentinsight_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# Force the dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# A fixed 256-bit (32-byte) hex-encoded string to ensure signatures remain valid across restarts
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
server.port = 8080


